version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_testephp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: acessphp
      MYSQL_USER: erasmo
      MYSQL_PASSWORD: 3727
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build: ./src
    container_name: php_testephp
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
